const Homeproduct = [
  {
    id: 1,
    Title: "Glaxay Tab s6 10.4-inch Android Tablet 128G",
    Cat: "Tablet",
    Price: "723$",
    img: "./img/tp1.jpg",
  },
  {
    id: 2,
    Title: "Tracker with IP67 Waterproof Smart Watch",
    Cat: "Smart Watch",
    Price: "168$",
    img: "./img/tp2.jpg",
  },
  {
    id: 3,
    Title: "Cancelling Headphones Wireless",
    Cat: "Headphone",
    Price: "49$",
    img: "./img/tp3.jpg",
  },
  {
    id: 4,
    Title: "Professional Camera 4K Digital Video Camera",
    Cat: "Camera",
    Price: "1049$",
    img: "./img/tp4.jpg",
  },
  {
    id: 5,
    Title: "Cpu Coloer 2Heat Pipes 12mm Pin PWM RGB for Intel",
    Cat: "Heat pipe",
    Price: "156$",
    img: "./img/tp5.jpg",
  },
  {
    id: 6,
    Title: "Glaxay Tab s6 10.4-inch Android Tablet 128G",
    Cat: "Tablet",
    Price: "723$",
    img: "./img/tp6.png",
  },
  {
    id: 7,
    Title: "PlayStation 4 2TB Slim Gaming Console",
    Cat: "Gaming",
    Price: "2098$",
    img: "./img/tp7.jpg",
  },
  {
    id: 8,
    Title: "Mini Portable Mobile Phone Powerbank for iphone",
    Cat: "Power Bank",
    Price: "386$",
    img: "./img/tp8.jpg",
  },
  {
    id: 9,
    Title: "Mini Portable Mobile Phone Powerbank for iphone",
    Cat: "Power Bank",
    Price: "386$",
    img: "./img/tp8.jpg",
  },
  {
    id: 10,
    Title: "Mini Portable Mobile Phone Powerbank for iphone",
    Cat: "Power Bank",
    Price: "386$",
    img: "./img/tp8.jpg",
  },
];
export default Homeproduct;
